// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from "next";
import { Product } from "../../product/types";

export type Data = {
  products: Product[];
};

const data: Data = {
  products: [
    {
      id: "1",
      name: "Mango",
      priceUnit: 3.0,
      priceKg: 6.0,
      weight: "600",
      unit: "ud",
      image: "/images/mango.jpg",
      imageModal: "/images/mango2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "2",
      name: "Pina",
      priceUnit: 6.0,
      priceKg: 3.0,
      weight: "800",
      unit: "ud",
      image: "/images/pina.jpg",
      imageModal: "/images/pina2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "3",
      name: "Granada",
      priceUnit: 2.6,
      priceKg: 3.0,
      weight: "300",
      unit: "ud",
      image: "/images/granada.jpg",
      imageModal: "/images/granada2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "4",
      name: "Repollo",
      priceUnit: 2.2,
      priceKg: 4.0,
      weight: "500",
      unit: "ud",
      image: "/images/repollo.jpg",
      imageModal: "/images/repollo2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "5",
      name: "Berenjena",
      priceUnit: 1.1,
      priceKg: 2.44,
      weight: "450",
      unit: "ud",
      image: "/images/berenjena.jpg",
      imageModal: "/images/berenjena2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "6",
      name: "Pan de trigo ",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/panTrigoBlanco.jpg",
      imageModal: "/images/panTrigoBlanco2.png",
      description: "",
      category: "offerts",
    },
    {
      id: "7",
      name: "Calabaza ",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/calabaza.jpg",
      imageModal: "/images/calabaza2.png",
      description: "",
      category: "popular",
    },
    {
      id: "8",
      name: "Pimiento rojo",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/pimiento-rojo.jpg",
      imageModal: "/images/pimiento-rojo2.png",
      description: "",
      category: "popular",
    },
    {
      id: "9",
      name: "huevos-ecologicos",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/huevos-ecologicos.jpg",
      imageModal: "/images/huevos-ecologicos2.png",
      description: "",
      category: "popular",
    },
    {
      id: "10",
      name: "Calabaza Maxima ",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/calabazaMaxima.jpg",
      imageModal: "/images/calabazaMaxima2.png",
      description: "",
      category: "popular",
    },
    {
      id: "11",
      name: "Cebolleta ",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/cebolleta.jpg",
      imageModal: "/images/cebolleta2.png",
      description: "",
      category: "popular",
    },
    {
      id: "12",
      name: "Pan de Hozaga ",
      priceUnit: 2.2,
      priceKg: 7.33,
      weight: "300",
      unit: "ud",
      image: "/images/panHogazaEspelta.jpg",
      imageModal: "/images/panHogazaEspelta2.png",
      description: "",
      category: "popular",
    },
  ],
};

export default function handler(
  req: NextApiRequest,
  res: NextApiResponse<Data>
) {
  res.status(200).json(data);
}
