import type { GetStaticProps } from 'next';
import Head from 'next/head';
import { Header, Hero, StoreLayout } from '../ui/layout';
import OffertsProducts from '../product/screens/OffertsProducts';
import PopularProducts from '../product/screens/PopularProducts';
import { Product } from '../product/types';
import { useEffect } from 'react';
import { useStore } from '../context/storeContext';
import { useApp } from '../context/appContext';
import { ModalProduct, ModalCart } from '../ui/modals';

type Props = {
  products: Product[];
};

const Home = ({ products }: Props) => {
  const { setProducts } = useStore();
  const {
    visibleModalProduct,
    visibleModalCart,
    changeVisibilityModalProduct,
    changeVisibilityModalCart,
    productSelected,
  } = useApp();
  useEffect(() => {
    setProducts(products);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header />
      <main>
        <Hero />
        <StoreLayout>
          <OffertsProducts />
          <PopularProducts />
        </StoreLayout>
      </main>
      <ModalProduct
        visible={visibleModalProduct}
        changeVisibility={changeVisibilityModalProduct}
        product={productSelected}
      />
      <ModalCart
        visible={visibleModalCart}
        changeVisibility={changeVisibilityModalCart}
      />
    </>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch(`${process.env.SERVER}/api/products`);
  const { products } = await response.json();
  return {
    props: {
      products,
    },
  };
};

export default Home;
